version: '3.7'

services:
  php-apache:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "9080:80"
    volumes:
      - ./:/var/www/html
    depends_on:
      - mysql
    networks:
      - my_network

  mysql:
    image: mysql
    environment:
      MYSQL_ROOT_PASSWORD: uptc2021
      MYSQL_DATABASE: simulador
    ports:
      - "3306:3306"
    networks:
      - my_network

networks:
  my_network:
    driver: bridge
