version: '3.7'

services:
  php-apache:
    image: my-apache2
    ports:
      - "9080:80"
    volumes:
      - :/usr/local/apache2/htdocs/
    depends_on:
      - mysql
    networks:
      - my_network

  mysql:
    image: mysql
    environment:
      MYSQL_ROOT_PASSWORD: uptc2021
      MYSQL_DATABASE: simulador
    volumes:
      - ./mysql:/var/lib/mysql
    ports:
      - "3307:3306"
    networks:
      - my_network

networks:
  my_network:
    driver: bridge
